project 'SwpCateGoryDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '7.0'

target 'SwpCateGoryDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwpCateGoryDemo
  
  inhibit_all_warnings!
  
  pod 'Masonry'         #   Masonry 自动布局框架
  pod 'SVProgressHUD'   #   提示信息库

end
